knp_snappy:
    pdf:
        enabled:    true
        binary:     '"C:\Users\ALPHA\Desktop\mehdi\wkhtmltopdf\bin\wkhtmltopdf"'
        options:
            no-outline: true
            page-size: LETTER
            encoding: UTF-8
    image:
        enabled:    true
        binary:     '"C:\Users\ALPHA\Desktop\mehdi\wkhtmltopdf\bin\wkhtmltoimage"'
        options:    []
