<?php

/* src/AppBundle/Repository/EntityRepository */

namespace AppBundle\Repository;

/**
 * EntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT nomEvent
                FROM Event:Entity e
                WHERE nomEvent LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
}